### ISSUE TITLE
Почему pyrob работает так медленно?

### ISSUE THREAD

**Issue by skorphil** [mipt-cs/pyrob#3]
Особенно, когда проверяет задания с большими полями, где нужно много чего закрашивать. Кажется, что это не rocket science :/ Это какая-то неоптимальная библиотека или сам python настолько тормозной? Но ведь на нем пишут гораздо более серьезные вещи

**Comment by fufler** [comment]
Есть ли какой-то конкретный пример ситуации, когда pyrob работает медленно?

**Comment by skorphil** [comment]
@fufler Он в принципе всегда при проверке выполненных заданий вначале очень медленно думает.
Ярче всего это проявилось при проверке Задача №20: task_4_3 - робот перемещался по полю ооочень медленно. чтобы проверить вё задание ему нужно было минут 10, наверное - не дождался.
Речь идет про проверку "в демонстрационном режиме", когда он рисует tkinter поле и двигается по нему.

Наверное, это какой-то лимит tkinter :/

**Comment by fufler** [comment]
При стандартных настройках у меня решение из этого репозитория работает вот так:


https://user-images.githubusercontent.com/566115/105637886-e4a86c80-5e80-11eb-8558-6c3469c5bd22.mp4



Если в качестве задержки при отрисовке поставить что-то типа `0.000001`, то решение проверяется меньше чем за секунду.

**Comment by skorphil** [comment]
@fufler ого, так круто. У меня он каждый шаг обдумывает секунд 5-10. Настройка задержки ни на что не влияет. osx 11.1, python 3.7.9

**Comment by skorphil** [comment]
@fufler я тут покопался и выяснил, что это от virtual environment зависит. В дефолтовом environment все работает шустро.
Но не понимаю, чем могут отличаться environment кроме как версией питона, а версия везде одинаковая у меня.

Попробовал склонировать окружение в котором все работает - и в клонированном тоже заработало. Значит это связано с какими-то пакетами :/ как можно определить, какой пакет или отсутствие какго пакета вызывает тормоза?

**Comment by fufler** [comment]
venv-ы могут отличаться как версиями самого Питона, так и пакетами и их версиями. Обычно один venv используется на один репозиторий. Не могу точно сказать, как можно диагностировать тормоза. Я бы сделал следующее:

1. Посмотрел бы профайлером (ну или обычными принтами), что именно тормозит. Есть предположение, что tkinter, но это надо проверять.
2. Потом погуглил бы баги по результатам профайлинга. Например, можно найти вот [такое](https://bugs.python.org/issue33500). Не утверждаю, что это ровно тот самый баг.
3. Ну и если это бы не дало результата, то уже начал бы пытаться убирать из venv-а пакеты до тех пор, пока тормоза не уйдут.

Тикет закрываю.

**Comment by skorphil** [comment]
@fufler Виновник тормозов - пакет tk версии 8.6.10. Пришлось даунгрейдить до tk 8.6.8, чтобы робот работал без тормозов
